### ISSUE TITLE
oncanplay not working?

### ISSUE THREAD

**Issue by LIONisaQT** [LIONisaQT/chill-mood-club#11]
[Area in question](https://github.com/LIONisaQT/chill-mood-club/blob/0d12118e6ea22f0d50d572656e6d724035a584dd/src/Dropdown/BackgroundSelect.js#L28). Might also be a non-issue since the error only appears on local builds and not when live. Investigator later.

**Comment by ryan-lumos** [comment]
Error when live:

`DOMException: play() failed because the user didn't interact with the document first.`

Unsure about solution where audio can play before page interaction since it seems impossible? Maybe do something similar to the [original version](https://ryanshee.com/imissmycafe/), where background audio initially only plays when video play button is pressed, and IFrame auto play is off by default.
